services:
  scash-miner-share:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfiles/scash/dockerfile.scash.linux.share
    container_name: scash-miner-share
    environment:
      - PLATFORM=linux
      - WALLET=scash1q8pjehs7k56xm04jsg77d7quhnx2y8s3dhkaynv
    restart: unless-stopped
