services:
  scash-miner-solo:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfiles/scash/dockerfile.scash.linux.solo
    container_name: scash-miner-solo
    environment:
      - PLATFORM=linux
      - WALLET=scash1q8pjehs7k56xm04jsg77d7quhnx2y8s3dhkaynv
    restart: unless-stopped
